CC=gcc
CFLAGS=-Wall -Wextra -Werror --std=c99
LDFLAGS=
EXEC= sandpile
SRC = 	./main.c \
	./fonction.c
OBJ = $(SRC:.c=.o)
NAME = sandpile

all: $(EXEC)

$(NAME): $(OBJ)
	$(CC) -o $(NAME) $(OBJ) $(LDFLAGS)

fonction.o: fonction.c
	$(CC) -o fonction.o -c fonction.c $(CFLAGS)

main.o: main.c fonction.h
	$(CC) -o main.o -c main.c $(CFLAGS)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re:	fclean all

.PHONY:	all clean fclean re